force-app/main/default/objects/Cell__c.object
<CustomObject>
    <description>Parcel cell</description>
    <fields>
        <fullName>Pin__c</fullName>
        <description>This should be a unique number among all cells orders</description>
        <label>PIN</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Cell</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/GeneratorPin.cls
public class GeneratorPin {
    public static String generateUniquePin() {
        String pin;
        Boolean isUnique = false;
        
        while (!isUnique) {
            pin = generatePin();
            Integer count = [SELECT COUNT() FROM Cell__c WHERE Pin__c = :pin LIMIT 1];
            if (count == 0) {
                isUnique = true;
            }
        }
        return pin;
    }
    
    private static String generatePin() {
        String chars = '0123456789';
        String pin = '';
        for (Integer i = 0; i < 6; i++) {
            Integer randIndex = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            pin += chars.substring(randIndex, randIndex + 1);
        } 
        return pin;
    }
}