force-app/main/default/objects/Cell__c.object
<CustomObject>
    <description>Parcel cell</description>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Empty</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ParcelLocker__c</fullName>
        <label>Parcel Locker</label>
        <referenceTo>ParcelLocker__c</referenceTo>
        <relationshipLabel>Cells</relationshipLabel>
        <relationshipName>Cells</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <description>Size of Cell</description>
        <label>Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cell</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-1</fullName>
            </value>
            <value>
                <fullName>A-2</fullName>
            </value>
            <value>
                <fullName>A-3</fullName>
            </value>
            <value>
                <fullName>A-4 (A-1)</fullName>
            </value>
            <value>
                <fullName>A-4 (A-2)</fullName>
            </value>
            <value>
                <fullName>A-4 (A-3)</fullName>
            </value>
            <value>
                <fullName>A-4 (B-1)</fullName>
            </value>
            <value>
                <fullName>A-4 (B-2)</fullName>
            </value>
            <value>
                <fullName>A-4 (B-3)</fullName>
            </value>
            <value>
                <fullName>A-5</fullName>
            </value>
            <value>
                <fullName>A-6</fullName>
            </value>
            <value>
                <fullName>B-1</fullName>
            </value>
            <value>
                <fullName>B-2</fullName>
            </value>
            <value>
                <fullName>B-3</fullName>
            </value>
            <value>
                <fullName>B-4 (A-1)</fullName>
            </value>
            <value>
                <fullName>B-4 (A-2)</fullName>
            </value>
            <value>
                <fullName>B-4 (A-3)</fullName>
            </value>
            <value>
                <fullName>B-4 (B-1)</fullName>
            </value>
            <value>
                <fullName>B-4 (B-2)</fullName>
            </value>
            <value>
                <fullName>B-4 (B-3)</fullName>
            </value>
            <value>
                <fullName>B-5</fullName>
            </value>
            <value>
                <fullName>B-6 (A-1)</fullName>
            </value>
            <value>
                <fullName>B-6 (A-2)</fullName>
            </value>
            <value>
                <fullName>B-6 (A-3)</fullName>
            </value>
            <value>
                <fullName>C-1</fullName>
            </value>
            <value>
                <fullName>C-2</fullName>
            </value>
            <value>
                <fullName>C-3</fullName>
            </value>
            <value>
                <fullName>C-4 (A-1)</fullName>
            </value>
            <value>
                <fullName>C-4 (A-2)</fullName>
            </value>
            <value>
                <fullName>C-4 (A-3)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ParcelLocker__c.object
<CustomObject>
    <description>This object represent Parcel Locker</description>
    <label>Parcel Locker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Parcel Locker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Lockers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ParcelLockerController.cls
public with sharing class ParcelLockerController {
    public class CellOption {
        @AuraEnabled
        public String label { get; set; }
        
        @AuraEnabled
        public String value { get; set; }

        public CellOption(String label, String value) {
            this.label = label;
            this.value = value;
        }
    }
    
    @AuraEnabled(cacheable=false)
    public static List<Cell__c> getCells(Id lockerId) {
      
        return [
            SELECT Id, Name, Position__c, Availability__c, ParcelLocker__c, Size__c, Status__c
            FROM Cell__c
            WHERE ParcelLocker__c = :lockerId
            ORDER BY Position__c
        ];
    }
    
    @AuraEnabled
    public static List<CellOption> getAvailableCells(Id parcelLockerId) {
        if (parcelLockerId == null) {
            throw new AuraHandledException('Parcel Locker ID cannot be null');
        }
   
        List<Cell__c> availableCells = [
            SELECT Id, Name, Position__c
            FROM Cell__c
            WHERE ParcelLocker__c = :parcelLockerId
            AND Availability__c = 'Empty'
            ORDER BY Name
        ];
   
        List<CellOption> options = new List<CellOption>();
        for (Cell__c cell : availableCells) {
            options.add(new CellOption(cell.Position__c, cell.Id));
        }
        return options;
    }
}