force-app/main/default/objects/Cell__c.object
<CustomObject>
    <description>Parcel cell</description>
    <label>Cell</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Depth__c.field-meta.xml
<CustomField>
    <fullName>Depth__c</fullName>
    <formula>48.5</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Depth (cm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <formula>CASE(TEXT(Size__c),
&quot;Small&quot;, 10,
&quot;Medium&quot;, 10,
&quot;Big&quot;, 14.6,
&quot;Large&quot;, 15.4,
&quot;Extra Large&quot;, 23.7,
&quot;Jumbo&quot;, 23.7,
&quot;Mega&quot;, 47.4,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Height (cm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cell__c/fields/Width__c.field-meta.xml
<CustomField>
    <fullName>Width__c</fullName>
    <formula>CASE(TEXT(Size__c),
&quot;Small&quot;, 16.4,
&quot;Medium&quot;, 33.2,
&quot;Big&quot;, 47.4,
&quot;Large&quot;, 47.4,
&quot;Extra Large&quot;, 47.4,
&quot;Jumbo&quot;, 47.4,
&quot;Mega&quot;, 47.4,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Width (cm)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CellOrder__c.object
<CustomObject>
    <description>Junction object between Cell, Order and Contact</description>
    <fields>
        <fullName>Cell__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cell</label>
        <referenceTo>Cell__c</referenceTo>
        <relationshipLabel>Cell Orders</relationshipLabel>
        <relationshipName>CellOrders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Cell Order</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Cell Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cell Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CellOrder__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cell Orders</relationshipLabel>
    <relationshipName>Cell_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order/fields/Parcel_Depth__c.field-meta.xml
<CustomField>
    <fullName>Parcel_Depth__c</fullName>
    <label>Parcel Depth</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Parcel_Height__c.field-meta.xml
<CustomField>
    <fullName>Parcel_Height__c</fullName>
    <description>Field stores the height of box (parcel).</description>
    <label>Parcel Height</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Parcel_Width__c.field-meta.xml
<CustomField>
    <fullName>Parcel_Width__c</fullName>
    <description>Field stores the width of box (parcel).</description>
    <label>Parcel Width</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CellOrderTriggerHelper.cls
public with sharing class CellOrderTriggerHelper {
    public void validateParcelDimensions(List<CellOrder__c> newOrders) {
        // Collecting all Ids for queries
        Set<Id> cellIds = new Set<Id>();
        Set<Id> orderIds = new Set<Id>();
        
        for (CellOrder__c cellOrder : newOrders) {
            cellIds.add(cellOrder.Cell__c);
            orderIds.add(cellOrder.Order__c);
        }
        
        Map<Id, Cell__c> cellsMap = new Map<Id, Cell__c>(
            [SELECT Width__c, Height__c, Depth__c FROM Cell__c WHERE Id IN :cellIds]
        );
        
        Map<Id, Order> ordersMap = new Map<Id, Order>(
            [SELECT Parcel_Width__c, Parcel_Height__c, Parcel_Depth__c FROM Order WHERE Id IN :orderIds]
        );
        
        for (CellOrder__c cellOrder : newOrders) {
            Cell__c cell = cellsMap.get(cellOrder.Cell__c);
            Order order = ordersMap.get(cellOrder.Order__c);
            
            //If Cell or Order is empty
            if (cell == null || order == null) {
                continue;
            }
            
            // Parcel dimensions
            Decimal parcelWidth = order.Parcel_Width__c;
            Decimal parcelHeight = order.Parcel_Height__c;
            Decimal parcelDepth = order.Parcel_Depth__c;
            
            // Cell dimensions
            Decimal cellWidth = cell.Width__c;
            Decimal cellHeight = cell.Height__c;
            Decimal cellDepth = cell.Depth__c;
            
            // Check orientation 
            Boolean fits = (
                (parcelDepth <= cellDepth && parcelWidth <= cellWidth && parcelHeight <= cellHeight) ||
                (parcelDepth <= cellDepth && parcelHeight <= cellWidth && parcelWidth <= cellHeight) ||
                (parcelWidth <= cellDepth && parcelDepth <= cellWidth && parcelHeight <= cellHeight) ||
                (parcelWidth <= cellDepth && parcelHeight <= cellWidth && parcelDepth <= cellHeight) ||
                (parcelHeight <= cellDepth && parcelWidth <= cellWidth && parcelDepth <= cellHeight) ||
                (parcelHeight <= cellDepth && parcelDepth <= cellWidth && parcelWidth <= cellHeight)
            );
            
            // If the parcel dimensions doesn't fit
            if (!fits) {
                cellOrder.Cell__c.addError('This cell is not large enough to store this package.');
            }
        }
    }
}