force-app/main/default/objects/Cell__c.object
<CustomObject>
    <description>Parcel cell</description>
    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Empty</fullName>
                </value>
                <value>
                    <fullName>Full</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ParcelLocker__c</fullName>
        <label>Parcel Locker</label>
        <referenceTo>ParcelLocker__c</referenceTo>
        <relationshipLabel>Cells</relationshipLabel>
        <relationshipName>Cells</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <description>Size of Cell</description>
        <label>Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cell</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Cell Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cell__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-1</fullName>
            </value>
            <value>
                <fullName>A-2</fullName>
            </value>
            <value>
                <fullName>A-3</fullName>
            </value>
            <value>
                <fullName>A-4 (A-1)</fullName>
            </value>
            <value>
                <fullName>A-4 (A-2)</fullName>
            </value>
            <value>
                <fullName>A-4 (A-3)</fullName>
            </value>
            <value>
                <fullName>A-4 (B-1)</fullName>
            </value>
            <value>
                <fullName>A-4 (B-2)</fullName>
            </value>
            <value>
                <fullName>A-4 (B-3)</fullName>
            </value>
            <value>
                <fullName>A-5</fullName>
            </value>
            <value>
                <fullName>A-6</fullName>
            </value>
            <value>
                <fullName>B-1</fullName>
            </value>
            <value>
                <fullName>B-2</fullName>
            </value>
            <value>
                <fullName>B-3</fullName>
            </value>
            <value>
                <fullName>B-4 (A-1)</fullName>
            </value>
            <value>
                <fullName>B-4 (A-2)</fullName>
            </value>
            <value>
                <fullName>B-4 (A-3)</fullName>
            </value>
            <value>
                <fullName>B-4 (B-1)</fullName>
            </value>
            <value>
                <fullName>B-4 (B-2)</fullName>
            </value>
            <value>
                <fullName>B-4 (B-3)</fullName>
            </value>
            <value>
                <fullName>B-5</fullName>
            </value>
            <value>
                <fullName>B-6 (A-1)</fullName>
            </value>
            <value>
                <fullName>B-6 (A-2)</fullName>
            </value>
            <value>
                <fullName>B-6 (A-3)</fullName>
            </value>
            <value>
                <fullName>C-1</fullName>
            </value>
            <value>
                <fullName>C-2</fullName>
            </value>
            <value>
                <fullName>C-3</fullName>
            </value>
            <value>
                <fullName>C-4 (A-1)</fullName>
            </value>
            <value>
                <fullName>C-4 (A-2)</fullName>
            </value>
            <value>
                <fullName>C-4 (A-3)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CellOrder__c.object
<CustomObject>
    <description>Junction object between Cell, Order and Contact</description>
    <fields>
        <fullName>Cell__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cell</label>
        <referenceTo>Cell__c</referenceTo>
        <relationshipLabel>Cell Orders</relationshipLabel>
        <relationshipName>CellOrders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cell Orders</relationshipLabel>
        <relationshipName>Cell_Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending delivery</fullName>
                    <default>true</default>
                    <label>Pending delivery</label>
                </value>
                <value>
                    <fullName>Delivering</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Cell Order</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Cell Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cell Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CellOrder__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cell Orders</relationshipLabel>
    <relationshipName>Cell_Orders</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CellOrder__c/fields/ParcelLocker__c.field-meta.xml
<CustomField>
    <fullName>ParcelLocker__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parcel Locker</label>
    <referenceTo>ParcelLocker__c</referenceTo>
    <relationshipLabel>Cell Orders</relationshipLabel>
    <relationshipName>Cell_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Parcel_Depth__c.field-meta.xml
<CustomField>
    <fullName>Parcel_Depth__c</fullName>
    <label>Parcel Depth</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Parcel_Height__c.field-meta.xml
<CustomField>
    <fullName>Parcel_Height__c</fullName>
    <description>Field stores the height of box (parcel).</description>
    <label>Parcel Height</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Parcel_Width__c.field-meta.xml
<CustomField>
    <fullName>Parcel_Width__c</fullName>
    <description>Field stores the width of box (parcel).</description>
    <label>Parcel Width</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ParcelLocker__c.object
<CustomObject>
    <description>This object represent Parcel Locker</description>
    <label>Parcel Locker</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Parcel Locker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parcel Lockers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CellOrderTriggerHandlerTest.cls
@isTest
public class CellOrderTriggerHandlerTest {
    @isTest
    static void testAfterInsert() {
        // Arrange
        ParcelLocker__c locker = new ParcelLocker__c(Name = '123', Location__Latitude__s = 37.7749, Location__Longitude__s = -122.4194);
        insert locker;
        
        Cell__c cell = new Cell__c(ParcelLocker__c = locker.Id, Availability__c = 'Empty', Status__c = 'Closed', Position__c = 'A-1', Size__c = 'Small');
        insert cell;
        
        Account account = new Account(Name = 'Test Account');
        insert account;
    
        Contract contract = new Contract(AccountId = account.Id, StartDate = Date.today());
        insert contract;
    
        Contact contact = new Contact(FirstName = 'John', LastName = 'Smith', AccountId = account.Id);
        insert contact;

        Order order = new Order(
            AccountId = account.Id,
            ContractId = contract.Id,
            Parcel_Width__c = 16,
            Parcel_Height__c = 9,
            Parcel_Depth__c = 47,
            EffectiveDate = Date.today(),
            Status = 'Draft'
        );
    	insert order;

        CellOrder__c cellOrder = new CellOrder__c(
            ParcelLocker__c = locker.Id,
            Cell__c = cell.Id,
            Order__c = order.Id,
            Contact__c = contact.Id,
            State__c = 'Delivered'
    	);
        // Disabling the trigger while testing
        CellOrderTriggerHandler.triggerIsDisabled = true;
		insert cellOrder;
		CellOrderTriggerHandler handler = new CellOrderTriggerHandler(true, 1);
        List<CellOrder__c> cellOrders = new List<CellOrder__c>{cellOrder};
        Map<Id, CellOrder__c> cellOrdersMap = new Map<Id, CellOrder__c>(cellOrders);
        
        // Act
        Test.startTest();
        handler.afterInsert(cellOrders, cellOrdersMap);
        Test.stopTest();
            
        // Assert
        System.assertEquals(0, cellOrders[0].getErrors().size(), 'No error should occur for valid dimensions.');
    }
    
    @isTest
    static void testAfterUpdate() {
        // Arrange
        ParcelLocker__c locker = new ParcelLocker__c(Name = '123', Location__Latitude__s = 37.7749, Location__Longitude__s = -122.4194);
        insert locker;
        
        Cell__c cell = new Cell__c(ParcelLocker__c = locker.Id, Availability__c = 'Empty', Status__c = 'Closed', Position__c = 'A-1', Size__c = 'Small');
        insert cell;
        
        Account account = new Account(Name = 'Test Account');
        insert account;
    
        Contract contract = new Contract(AccountId = account.Id, StartDate = Date.today());
        insert contract;
    
        Contact contact = new Contact(FirstName = 'John', LastName = 'Smith', AccountId = account.Id);
        insert contact;

        Order existingOrder = new Order(
            AccountId = account.Id,
            ContractId = contract.Id,
            Parcel_Width__c = 5,
            Parcel_Height__c = 8,
            Parcel_Depth__c = 10,
            EffectiveDate = Date.today(),
            Status = 'Draft'
        );
    	insert existingOrder;

        CellOrder__c existingCellOrder = new CellOrder__c(
            ParcelLocker__c = locker.Id,
            Order__c = existingOrder.Id,
            Contact__c = contact.Id,
            State__c = 'Pending delivery'
    	);
        insert existingCellOrder;
        
        Order newOrder = new Order(
            AccountId = account.Id,
            ContractId = contract.Id,
            Parcel_Width__c = 15,
            Parcel_Height__c = 9,
            Parcel_Depth__c = 47,
            EffectiveDate = Date.today(),
            Status = 'Draft'
        );
        // Disabling the trigger while testing
        CellOrderTriggerHandler.triggerIsDisabled = true;
        insert newOrder;
        CellOrder__c updatedCellOrder = existingCellOrder;
        updatedCellOrder.Order__c = newOrder.Id;
       	update updatedCellOrder;
        
        List<CellOrder__c> oldCellOrders = new List<CellOrder__c>{existingCellOrder};
        List<CellOrder__c> newCellOrders = new List<CellOrder__c>{updatedCellOrder};
        
        Map<Id, CellOrder__c> oldCellOrdersMap = new Map<Id, CellOrder__c>(oldCellOrders);
        Map<Id, CellOrder__c> newCellOrdersMap = new Map<Id, CellOrder__c>(newCellOrders);
        
        CellOrderTriggerHandler handler = new CellOrderTriggerHandler(true, 1);
        
        // Act
        Test.startTest();
        handler.afterUpdate(oldCellOrders, newCellOrders, oldCellOrdersMap, newCellOrdersMap);
        Test.stopTest();
        
        // Assert
        System.assertEquals(0, newCellOrders[0].getErrors().size(), 'No error should occur for valid dimensions.'); 
    }
}